kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55
    pull: always
    url: https://kyoto.ongakusei.tokyo
    validate: true

- name: deploy
  image: plugins/s3-sync:1
  settings:
    bucket: kyoto.ongakusei.tokyo
    access_key: 
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    region: ap-northeast-1
    source: public/
    target: /
